Quinlan.Web.MVC/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Quinlan.MVC.Models;
using Quinlan.MVC.Services;
using System;

namespace Quinlan.MVC.Controllers
{
    public class PeopleController : Controller
    {
        private static IDetailsService<PersonDetails> _personDetailsService;
        private static IEditService<PersonEdit> _personEditService;
        private static IFormService<PersonViewModel> _personFormService;
        private static IIndexService<PersonIndex,PersonFilterOptionsViewModel> _personIndexService;

        public PeopleController(IDetailsService<PersonDetails> personDetailsService , IEditService<PersonEdit> personEditService, IFormService<PersonViewModel> personFormService, IIndexService<PersonIndex, PersonFilterOptionsViewModel> personIndexService )
        {
            _personDetailsService = personDetailsService;
            _personEditService = personEditService;
            _personFormService = personFormService;
            _personIndexService = personIndexService;
        }

        [Authorize]
        public IActionResult Details(int id)
        {
            var vm = _personDetailsService.Build(id, null, User.IsInRole("Owner"));

            return View(vm);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Details(int id, CardFilterOptionsViewModel filterOptions)
        {
            var vm = _personDetailsService.Build(id, filterOptions, User.IsInRole("Owner"));

            return View(vm);
        }
        [Authorize]
        public IActionResult Index()
        {
            var peopleVM = _personIndexService.Build(null);

            return View(peopleVM);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Index(PersonFilterOptionsViewModel personFilterOptionsViewModel)
        {
            var peopleVM = _personIndexService.Build(personFilterOptionsViewModel);

            return View(peopleVM);
        }
        [Authorize(Roles = "Owner")]
        public IActionResult Edit(int id)
        {
            var peopleVM = _personEditService.Build(id);

            return View(peopleVM);
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Edit(int id, PersonViewModel personVM)
        {
            // id value is not hidden in form
            personVM.Id = id;

            bool isValid = TryValidateModel(personVM);

            if (isValid)
            {
                try
                {
                    _personFormService.Save(id, personVM);

                    return RedirectToAction("Details",  new { id = id } );
                }
                catch
                {
                    throw new Exception("Save failed.");
                }
            }
            var vm = _personEditService.Build(id);

            return View(vm);
        }
    }
}

Quinlan.Web.MVC/Controllers/ProductsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Quinlan.MVC.Models;
using Quinlan.MVC.Services;

namespace Quinlan.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ILogger<CardsController> _logger;

        private static IIndexService<ProductIndex,ProductFilterOptionsViewModel> _productIndexService;
        private static IDetailsService<ProductDetails> _productDetailsService;
        public ProductsController(ILogger<CardsController> logger, IIndexService<ProductIndex,ProductFilterOptionsViewModel> productIndexService, IDetailsService<ProductDetails> productDetailsService)
        {
            _logger = logger;
            _productIndexService = productIndexService;
            _productDetailsService = productDetailsService;
        }
        public IActionResult Index()
        {
            try
            {
                var vm = _productIndexService.Build(null);

                return View(vm);
            }
            catch (Exception ex)
            {
                _logger.Log(LogLevel.Error, ex.Message);

                throw ex;
            }
        }
        public IActionResult Details(int id)
        {
            var vm = _productDetailsService.Build(id, null, User.IsInRole("Owner"));

            return View(vm);
        }
    }
}

Quinlan.Web.MVC/Views/Products/Details.cshtml
@model ProductDetails

@{
    ViewData["Title"] = @Model.DisplayName;
}


    <section id="headerSection">
        <h1>@Model.DisplayName</h1>

        @if (Model.HasOwnerRights)
        {
            <div style="float:left">
                <a asp-area="" asp-controller="People" asp-action="Edit" asp-route-id=@Model.Id>[Edit]</a>
            </div>
        }
        <div style="float:left">
            <h3>@Model.Price</h3>
        </div>
        <div style="clear:both"></div>
    </section>

<hr />

<section id="bodySection" style="width: 100%">

    <table style="font-size:9pt; width:100%">

        <tr>
            <th class="YearColumn ColumnHeader">
                Year
            </th>
            <th class="CompanyColumn ColumnHeader">
                Company / Set
            </th>
            <th class="CardNumberColumn ColumnHeader">
                Card #
            </th>
            <th class="AttributesColumn ColumnHeader">
                Attributes
            </th>
            <th class="PersonColumn ColumnHeader">
                Person
            </th>
            <th class="TeamColumn ColumnHeader">
                Team
            </th>
            <th class="GradeColumn ColumnHeader">
                Grade
            </th>
            <th class="ValueColumn ColumnHeader">
                Value
            </th>
        </tr>

        @foreach (var card in Model.Cards)
        {
            <tr>
                <td class="YearColumn">
                    @card.Year
                </td>
                <td class="CompanyColumn">
                    @card.Company
                </td>
                <td class="CardNumberColumn">
                    @card.CardNumber
                </td>
                <td class="AttributesColumn">
                    @card.Attributes
                </td>
                <td class="PersonColumn">
                    @card.PersonName
                </td>
                <td class="TeamColumn">
                    @card.TeamName
                </td>
                <td class="GradeColumn">
                    @card.Grade
                </td>
                <td class="ValueColumn">
                    @card.FormattedValue
                </td>
            </tr>
        }
    </table>

</section>

Quinlan.Web.MVC/Views/Products/Index.cshtml
@model ProductIndex

@{
    ViewData["Title"] = "People Finder Page";
}

<section id="bodySection">
    <h1>Products</h1>
</section>

<hr />

<section id="bodySection" style="width: 100%">

    <table style="font-size:9pt; width:100%">

        <tr>
            <th class="ColumnHeader">
                Name
            </th>
        </tr>

        @foreach (var product in Model.Products)
        {
        <tr>
            <td style="width:20%">
                <a asp-area="" asp-controller="Products" asp-action="Details" asp-route-id=@product.Id>@product.Description</a>
            </td>
        </tr>
        }
    </table>

</section>