Quinlan.Web.MVC/Models/Binding VMs/MagazineViewModel.cs
namespace Quinlan.MVC.Models
{
    public class MagazineViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Quinlan.Web.MVC/Controllers/MagazinesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Quinlan.MVC.Models;
using Quinlan.MVC.Services;

namespace Quinlan.Controllers
{
    [Authorize(Roles = "Nobody")]
    public class MagazinesController : Controller
    {
        private static IIndexService<MagazineIndex, MagazineFilterOptionsViewModel> _magazineIndexModelService;
        public MagazinesController(IIndexService<MagazineIndex, MagazineFilterOptionsViewModel> magazineIndexModelService)
        {
            _magazineIndexModelService = magazineIndexModelService;
        }
        public IActionResult Index()
        {
            var vm = _magazineIndexModelService.Build(null);

            return View(vm);
        }
        [HttpPost]
        public IActionResult Index(MagazineFilterOptionsViewModel filterOptions)
        {
            var vm = _magazineIndexModelService.Build(filterOptions);

            return View(vm);
        }
    }
}

Quinlan.Web.MVC/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Quinlan.MVC.Models;
using Quinlan.MVC.Services;
using System;

namespace Quinlan.MVC.Controllers
{
    public class PeopleController : Controller
    {
        private static IDetailsService<PersonDetails> _personDetailsService;
        private static IEditService<PersonEdit> _personEditService;
        private static IFormService<PersonViewModel> _personFormService;
        private static IIndexService<PersonIndex,PersonFilterOptionsViewModel> _personIndexService;

        public PeopleController(IDetailsService<PersonDetails> personDetailsService , IEditService<PersonEdit> personEditService, IFormService<PersonViewModel> personFormService, IIndexService<PersonIndex, PersonFilterOptionsViewModel> personIndexService )
        {
            _personDetailsService = personDetailsService;
            _personEditService = personEditService;
            _personFormService = personFormService;
            _personIndexService = personIndexService;
        }

        [Authorize]
        public IActionResult Details(int id)
        {
            var vm = _personDetailsService.Build(id, null, User.IsInRole("Owner"));

            return View(vm);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Details(int id, CardFilterOptionsViewModel filterOptions)
        {
            var vm = _personDetailsService.Build(id, filterOptions, User.IsInRole("Owner"));

            return View(vm);
        }
        [Authorize]
        public IActionResult Index()
        {
            var peopleVM = _personIndexService.Build(null);

            return View(peopleVM);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Index(PersonFilterOptionsViewModel personFilterOptionsViewModel)
        {
            var peopleVM = _personIndexService.Build(personFilterOptionsViewModel);

            return View(peopleVM);
        }
        [Authorize(Roles = "Owner")]
        public IActionResult Edit(int id)
        {
            var peopleVM = _personEditService.Build(id);

            return View(peopleVM);
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Edit(int id, PersonViewModel personVM)
        {
            // id value is not hidden in form
            personVM.Id = id;

            bool isValid = TryValidateModel(personVM);

            if (isValid)
            {
                try
                {
                    _personFormService.Save(id, personVM);

                    return RedirectToAction("Details",  new { id = id } );
                }
                catch
                {
                    throw new Exception("Save failed.");
                }
            }
            var vm = _personEditService.Build(id);

            return View(vm);
        }
    }
}

Quinlan.Web.MVC/Views/Magazines/Index.cshtml
@model MagazineIndex

@{
    ViewData["Title"] = @Model.DisplayName;
}



<section id="bodySection">
    <h1>@Model.DisplayName</h1>
</section>

<section id="filterSection">

    <form asp-controller="Magazines" asp-action="Index">


        <section id="column1" style="float:left; width:30%">

            <section id="personFilter">
                <label style="float:left">Person</label>
                <select style="float:left" asp-for="@Model.FilterOptions.PersonId" asp-items="@Model.People">
                </select>

                <div style="clear:both"></div>
            </section>

        </section>

        <section id="column2" style="float:left; width:30%">

            <section id="hofFilter">
                <input id="hofCheckBox" type="checkbox" style="float:left;" asp-for="@Model.FilterOptions.HOFFlag" />
                <label id="hofLabel" for="hofCheckBox" style="float:left;">Hall of Famers Only</label>

                <div style="clear: both"></div>
            </section>

            <section id="heismanFilter">
                <input id="heismanCheckBox" type="checkbox" style="float:left" asp-for="@Model.FilterOptions.HeismanFlag" />
                <label id="heismanLabel" for="heismanCheckBox" style="float: left">Heisman Winners Only</label>

                <div style="clear:both"></div>
            </section>

            <section id="notableFilter">
                <input id="notableCheckBox" type="checkbox" style="float:left" asp-for="@Model.FilterOptions.NotableFlag" />
                <label id="notableLabel" for="notableCheckBox" style="float:left">Notables Only</label>

                <div style="clear:both"></div>
            </section>

        </section>

        <section id="column3" style="float:left; width:10%">
            <nav id="buttons">
                <button type="submit">Search</button>
            </nav>
        </section>


        <div style="clear:both"></div>


    </form>

</section>

<hr />


<section id="bodySection" style="width: 100%">

    <table style="font-size:9pt; width:100%">

        <tr>
            <th class="YearColumn ColumnHeader">
                Year
            </th>
            <th class="CompanyColumn ColumnHeader">
                Company
            </th>
            <th class="PersonColumn ColumnHeader">
                Person
            </th>
            <th class="HOFColumn ColumnHeader">
                HOF
            </th>
            <th class="CostColumn ColumnHeader">
                Cost
            </th>
            <th class="ValueColumn ColumnHeader">
                Value
            </th>
        </tr>

        @foreach (var magazine in Model.Magazines)
        {
            <tr>
                <td class="YearColumn">
                    @magazine.Year
                </td>
                <td class="CompanyColumn">
                    @magazine.PublisherName
                </td>
                <td class="PersonColumn">
                    @if (magazine.PersonId > 0)
                    {
                    <a asp-area="" asp-controller="People" asp-action="Details" asp-route-id=@magazine.PersonId>@magazine.PersonName</a>
                    }
                    else
                    {
                        <div>&nbsp;</div>
                    }
                </td>
                <td class="HOFColumn">
                    @if (magazine.HOF == "HOF")
                    {
                        @magazine.HOF
                    }
                    else
                    {
                        <div>&nbsp;</div>
                    }
                </td>
                <td class="CostColumn">
                    @magazine.Cost.ToString("c")
                </td>
                <td class="ValueColumn">
                    @magazine.Value.ToString("c")
                </td>
            </tr>
        }
    </table>

</section>