Quinlan.Web.MVC/Models/Binding VMs/CollegeViewModel.cs
namespace Quinlan.MVC.Models
{
    public class CollegeViewModel
    {
        public int Id { get; set; }
        public string Identifier { get; set; }
        public string Name { get; set; }
        public string Nickname { get; set; }

    }
}

Quinlan.Web.MVC/Controllers/CardsController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Quinlan.MVC.Models;
using Quinlan.MVC.Services;

namespace Quinlan.Controllers
{
    public class CardsController : Controller
    {
        private readonly ILogger<CardsController> _logger;

        private static IViewService<CardView> _cardViewService;
        private static IEditService<CardEdit> _cardEditService;
        private static IFormService<CardViewModel> _cardFormService;
        public CardsController(ILogger<CardsController> logger, IViewService<CardView> cardViewService, IEditService<CardEdit> cardEditService, IFormService<CardViewModel> cardFormService)
        {
            _logger = logger;
            _cardViewService = cardViewService;
            _cardEditService = cardEditService;
            _cardFormService = cardFormService;
        }

        public IActionResult View(int id)
        {
            try
            {
                var vm = _cardViewService.Build(id);

                return View(vm);
            }
            catch (Exception ex)
            {
                _logger.Log(LogLevel.Error, ex.Message);

                throw ex;
            }
        }

        [Authorize(Roles = "Owner")]
        public IActionResult Edit(int id)
        {
            var cardVM = _cardEditService.Build(id);

            return View(cardVM);
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Edit(int id, CardViewModel cardVM)
        {
            // id value is not hidden in form
            cardVM.Id = id;

            bool isValid = TryValidateModel(cardVM);

            if (isValid)
            {
                try
                {
                    _cardFormService.Save(id, cardVM);

                    return RedirectToAction("Details", new { id = id });
                }
                catch
                {
                    throw new Exception("Save failed.");
                }
            }
            var vm = _cardEditService.Build(id);

            return View(vm);
        }
    }
}

Quinlan.Web.MVC/Controllers/CollegesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Quinlan.MVC.Models;
using Quinlan.MVC.Services;
using System;

namespace Quinlan.MVC.Controllers
{
    public class CollegesController : Controller
    {
        private static IDetailsService<CollegeDetails> _collegeDetailsService;
        private static IEditService<CollegeEdit> _collegeEditService;
        private static IFormService<CollegeViewModel> _collegeFormService;
        public CollegesController(IDetailsService<CollegeDetails> collegeDetailsService, IEditService<CollegeEdit> collegeEditService, IFormService<CollegeViewModel> collegeFormService)
        {
            _collegeDetailsService = collegeDetailsService;
            _collegeEditService = collegeEditService;
            _collegeFormService = collegeFormService;
        }

        [Authorize]
        public IActionResult Details(int id)
        {
            var vm = _collegeDetailsService.Build(id, null, User.IsInRole("Owner"));

            return View(vm);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Details(int id, CardFilterOptionsViewModel filterOptions)
        {
            var vm = _collegeDetailsService.Build(id, filterOptions, User.IsInRole("Owner"));

            return View(vm);
        }

        [Authorize(Roles = "Owner")]
        public IActionResult Edit(int id)
        {
            var collegeVM = _collegeEditService.Build(id);

            return View(collegeVM);
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Edit(int id, CollegeViewModel collegeVM)
        {
            // id value is not hidden in form
            collegeVM.Id = id;

            bool isValid = TryValidateModel(collegeVM);

            if (isValid)
            {
                try
                {
                    _collegeFormService.Save(id, collegeVM);

                    return RedirectToAction("Details", new { id = id });
                }
                catch
                {
                    throw new Exception("Save failed.");
                }
            }
            var vm = _collegeEditService.Build(id);

            return View(vm);
        }
    }
}

Quinlan.Web.MVC/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Quinlan.MVC.Models;
using Quinlan.MVC.Services;
using System;

namespace Quinlan.MVC.Controllers
{
    public class PeopleController : Controller
    {
        private static IDetailsService<PersonDetails> _personDetailsService;
        private static IEditService<PersonEdit> _personEditService;
        private static IFormService<PersonViewModel> _personFormService;
        private static IIndexService<PersonIndex,PersonFilterOptionsViewModel> _personIndexService;

        public PeopleController(IDetailsService<PersonDetails> personDetailsService , IEditService<PersonEdit> personEditService, IFormService<PersonViewModel> personFormService, IIndexService<PersonIndex, PersonFilterOptionsViewModel> personIndexService )
        {
            _personDetailsService = personDetailsService;
            _personEditService = personEditService;
            _personFormService = personFormService;
            _personIndexService = personIndexService;
        }

        [Authorize]
        public IActionResult Details(int id)
        {
            var vm = _personDetailsService.Build(id, null, User.IsInRole("Owner"));

            return View(vm);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Details(int id, CardFilterOptionsViewModel filterOptions)
        {
            var vm = _personDetailsService.Build(id, filterOptions, User.IsInRole("Owner"));

            return View(vm);
        }
        [Authorize]
        public IActionResult Index()
        {
            var peopleVM = _personIndexService.Build(null);

            return View(peopleVM);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Index(PersonFilterOptionsViewModel personFilterOptionsViewModel)
        {
            var peopleVM = _personIndexService.Build(personFilterOptionsViewModel);

            return View(peopleVM);
        }
        [Authorize(Roles = "Owner")]
        public IActionResult Edit(int id)
        {
            var peopleVM = _personEditService.Build(id);

            return View(peopleVM);
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Edit(int id, PersonViewModel personVM)
        {
            // id value is not hidden in form
            personVM.Id = id;

            bool isValid = TryValidateModel(personVM);

            if (isValid)
            {
                try
                {
                    _personFormService.Save(id, personVM);

                    return RedirectToAction("Details",  new { id = id } );
                }
                catch
                {
                    throw new Exception("Save failed.");
                }
            }
            var vm = _personEditService.Build(id);

            return View(vm);
        }
    }
}

Quinlan.Web.MVC/Controllers/TeamsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Quinlan.MVC.Models;
using Quinlan.MVC.Services;
using System;

namespace Quinlan.MVC.Controllers
{
    public class TeamsController : Controller
    {
        private static IDetailsService<TeamDetails> _teamDetailsService;
        private static IEditService<TeamEdit> _teamEditService;
        private static IFormService<TeamViewModel> _teamFormService;
        private static IIndexService<TeamIndex, TeamFilterOptionsViewModel> _teamIndexService;
       
        public TeamsController(IDetailsService<TeamDetails> teamDetailsService, IEditService<TeamEdit> teamEditService, IFormService<TeamViewModel> teamFormService, IIndexService<TeamIndex, TeamFilterOptionsViewModel> teamIndexService)
        {
            _teamDetailsService = teamDetailsService;
            _teamEditService = teamEditService;
            _teamFormService = teamFormService;
            _teamIndexService = teamIndexService;
        }

        [Authorize]
        public IActionResult Details(int id)
        {
            var vm = _teamDetailsService.Build(id, null, User.IsInRole("Owner"));

            return View(vm);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Details(int id, CardFilterOptionsViewModel filterOptions)
        {
            var vm = _teamDetailsService.Build(id, filterOptions, User.IsInRole("Owner"));

            return View(vm);
        }

        [Authorize]
        public IActionResult Index()
        {
            var teamVM = _teamIndexService.Build(null);

            return View(teamVM);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Index(TeamFilterOptionsViewModel teamFilterOptionsViewModel)
        {
            var teamVM = _teamIndexService.Build(teamFilterOptionsViewModel);

            return View(teamVM);
        }

        [Authorize(Roles = "Owner")]
        public IActionResult Edit(int id)
        {
            var teamVM = _teamEditService.Build(id);

            return View(teamVM);
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Edit(int id, TeamViewModel teamVM)
        {
            // id value is not hidden in form
            teamVM.Id = id;

            bool isValid = TryValidateModel(teamVM);

            if (isValid)
            {
                try
                {
                    _teamFormService.Save(id, teamVM);

                    return RedirectToAction("Details", new { id = id });
                }
                catch
                {
                    throw new Exception("Save failed.");
                }
            }
            var vm = _teamEditService.Build(id);

            return View(vm);
        }
    }
}

Quinlan.Web.MVC/Views/Colleges/Details.cshtml
@model CollegeDetails

@{
    ViewData["Title"] = @Model.DisplayName;
}



    <section id="headerSection">
        <h1 style="float:left">@Model.DisplayName</h1>

        @if (Model.HasOwnerRights)
        {
            <div style="float:left">
                <a asp-area="" asp-controller="Colleges" asp-action="Edit" asp-route-id=@Model.Id>[Edit]</a>
            </div>
        }

        <div style="clear:both"></div>
    </section>

<section id="filterSection">

    <form asp-controller="Colleges" asp-action="Details" asp-route-id="@Model.Id">

        @await Html.PartialAsync("~/Views/Shared/_FilterOptions.cshtml", @Model.FilterOptionsVM)

    </form>

</section>

<hr />

<section id="totalsSection">

    @await Html.PartialAsync("~/Views/Shared/_SearchTotals.cshtml", @Model.SearchTotalsVM)

</section>

<hr />

<section id="bodySection" style="width: 100%">

    <table style="font-size:9pt; width:100%">

        <tr>
            <th></th>
            <th class="YearColumn">
                Year
            </th>
            <th class="CompanyColumn">
                Company
            </th>
            <th class="CardNumberColumn">
                Card #
            </th>
            <th class="AttributesColumn">
                Attributes
            </th>
            <th class="PersonColumn">
                Person
            </th>

            <th class="TeamColumn">
                Team
            </th>
            <th class="HOFColumn">
                Grade
            </th>
            @if (Model.HasOwnerRights)
            {
                <th class="CostColumn">
                    Cost
                </th>
            }
            <th class="ValueColumn">
                Value
            </th>
        </tr>

        @foreach (var card in Model.Cards)
        {
    <tr>
        <td class="ViewColumn">
            <a asp-area="" asp-controller="Cards" asp-action="View" asp-route-id=@card.Id>[View]</a>
        </td>
        <td class="YearColumn">
            @card.Year
        </td>
        <td class="CompanyColumn">
            @card.Company
        </td>
        <td class="CardNumberColumn">
            @card.CardNumber
        </td>

        <td class="AttributesColumn">
            @card.Attributes
        </td>
        <td class="PersonColumn">
            <a asp-area="" asp-controller="People" asp-action="Details" asp-route-id=@card.PersonId>@card.PersonName</a> @card.HOF
        </td>
        <td class="TeamColumn">
            <a asp-area="" asp-controller="Teams" asp-action="Details" asp-route-id=@card.TeamId>@card.TeamName</a>
        </td>
        <td class="GradeColumn">
            @card.Grade
        </td>
        @if (Model.HasOwnerRights)
        {
            <td class="CostColumn">
                @card.FormattedCost
            </td>
        }
        <td class="ValueColumn">
            @card.FormattedValue
        </td>
    </tr>
        }
    </table>

</section>

Quinlan.Web.MVC/Views/Colleges/Edit.cshtml
@model CollegeEdit

@{
    ViewData["Title"] = @Model.DisplayName;
}

<section id="bodySection">
    <h1>@Model.DisplayName</h1>
</section>

<form asp-action="Edit" asp-controller="Colleges">

    <div>
        <input type="hidden" asp-for="@Model.CollegeVM.Identifier" />
    </div>
    <div>
        <label asp-for="@Model.CollegeVM.Name"></label>
        <input asp-for="@Model.CollegeVM.Name" />
        <span asp-validation-for="@Model.CollegeVM.Name"></span>
    </div>
    <div>
        <label asp-for="@Model.CollegeVM.Nickname"></label>
        <input asp-for="@Model.CollegeVM.Nickname" />
        <span asp-validation-for="@Model.CollegeVM.Nickname"></span>
    </div>

    <button type="submit">Save</button>
</form>